// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: iris/iris.proto

package iris

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IrisClient is the client API for Iris service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IrisClient interface {
	Span(ctx context.Context, in *SpanRequest, opts ...grpc.CallOption) (*SpanResponse, error)
	StateSyncEvents(ctx context.Context, in *StateSyncEventsRequest, opts ...grpc.CallOption) (Iris_StateSyncEventsClient, error)
	FetchCheckpoint(ctx context.Context, in *FetchCheckpointRequest, opts ...grpc.CallOption) (*FetchCheckpointResponse, error)
	FetchCheckpointCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FetchCheckpointCountResponse, error)
	FetchMilestone(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FetchMilestoneResponse, error)
	FetchMilestoneCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FetchMilestoneCountResponse, error)
	FetchLastNoAckMilestone(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FetchLastNoAckMilestoneResponse, error)
	FetchNoAckMilestone(ctx context.Context, in *FetchMilestoneNoAckRequest, opts ...grpc.CallOption) (*FetchMilestoneNoAckResponse, error)
	FetchMilestoneID(ctx context.Context, in *FetchMilestoneIDRequest, opts ...grpc.CallOption) (*FetchMilestoneIDResponse, error)
}

type irisClient struct {
	cc grpc.ClientConnInterface
}

func NewIrisClient(cc grpc.ClientConnInterface) IrisClient {
	return &irisClient{cc}
}

func (c *irisClient) Span(ctx context.Context, in *SpanRequest, opts ...grpc.CallOption) (*SpanResponse, error) {
	out := new(SpanResponse)
	err := c.cc.Invoke(ctx, "/iris.Iris/Span", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *irisClient) StateSyncEvents(ctx context.Context, in *StateSyncEventsRequest, opts ...grpc.CallOption) (Iris_StateSyncEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Iris_ServiceDesc.Streams[0], "/iris.Iris/StateSyncEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &irisStateSyncEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Iris_StateSyncEventsClient interface {
	Recv() (*StateSyncEventsResponse, error)
	grpc.ClientStream
}

type irisStateSyncEventsClient struct {
	grpc.ClientStream
}

func (x *irisStateSyncEventsClient) Recv() (*StateSyncEventsResponse, error) {
	m := new(StateSyncEventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *irisClient) FetchCheckpoint(ctx context.Context, in *FetchCheckpointRequest, opts ...grpc.CallOption) (*FetchCheckpointResponse, error) {
	out := new(FetchCheckpointResponse)
	err := c.cc.Invoke(ctx, "/iris.Iris/FetchCheckpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *irisClient) FetchCheckpointCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FetchCheckpointCountResponse, error) {
	out := new(FetchCheckpointCountResponse)
	err := c.cc.Invoke(ctx, "/iris.Iris/FetchCheckpointCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *irisClient) FetchMilestone(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FetchMilestoneResponse, error) {
	out := new(FetchMilestoneResponse)
	err := c.cc.Invoke(ctx, "/iris.Iris/FetchMilestone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *irisClient) FetchMilestoneCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FetchMilestoneCountResponse, error) {
	out := new(FetchMilestoneCountResponse)
	err := c.cc.Invoke(ctx, "/iris.Iris/FetchMilestoneCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *irisClient) FetchLastNoAckMilestone(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FetchLastNoAckMilestoneResponse, error) {
	out := new(FetchLastNoAckMilestoneResponse)
	err := c.cc.Invoke(ctx, "/iris.Iris/FetchLastNoAckMilestone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *irisClient) FetchNoAckMilestone(ctx context.Context, in *FetchMilestoneNoAckRequest, opts ...grpc.CallOption) (*FetchMilestoneNoAckResponse, error) {
	out := new(FetchMilestoneNoAckResponse)
	err := c.cc.Invoke(ctx, "/iris.Iris/FetchNoAckMilestone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *irisClient) FetchMilestoneID(ctx context.Context, in *FetchMilestoneIDRequest, opts ...grpc.CallOption) (*FetchMilestoneIDResponse, error) {
	out := new(FetchMilestoneIDResponse)
	err := c.cc.Invoke(ctx, "/iris.Iris/FetchMilestoneID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IrisServer is the server API for Iris service.
// All implementations must embed UnimplementedIrisServer
// for forward compatibility
type IrisServer interface {
	Span(context.Context, *SpanRequest) (*SpanResponse, error)
	StateSyncEvents(*StateSyncEventsRequest, Iris_StateSyncEventsServer) error
	FetchCheckpoint(context.Context, *FetchCheckpointRequest) (*FetchCheckpointResponse, error)
	FetchCheckpointCount(context.Context, *emptypb.Empty) (*FetchCheckpointCountResponse, error)
	FetchMilestone(context.Context, *emptypb.Empty) (*FetchMilestoneResponse, error)
	FetchMilestoneCount(context.Context, *emptypb.Empty) (*FetchMilestoneCountResponse, error)
	FetchLastNoAckMilestone(context.Context, *emptypb.Empty) (*FetchLastNoAckMilestoneResponse, error)
	FetchNoAckMilestone(context.Context, *FetchMilestoneNoAckRequest) (*FetchMilestoneNoAckResponse, error)
	FetchMilestoneID(context.Context, *FetchMilestoneIDRequest) (*FetchMilestoneIDResponse, error)
	mustEmbedUnimplementedIrisServer()
}

// UnimplementedIrisServer must be embedded to have forward compatible implementations.
type UnimplementedIrisServer struct {
}

func (UnimplementedIrisServer) Span(context.Context, *SpanRequest) (*SpanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Span not implemented")
}
func (UnimplementedIrisServer) StateSyncEvents(*StateSyncEventsRequest, Iris_StateSyncEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StateSyncEvents not implemented")
}
func (UnimplementedIrisServer) FetchCheckpoint(context.Context, *FetchCheckpointRequest) (*FetchCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchCheckpoint not implemented")
}
func (UnimplementedIrisServer) FetchCheckpointCount(context.Context, *emptypb.Empty) (*FetchCheckpointCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchCheckpointCount not implemented")
}
func (UnimplementedIrisServer) FetchMilestone(context.Context, *emptypb.Empty) (*FetchMilestoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMilestone not implemented")
}
func (UnimplementedIrisServer) FetchMilestoneCount(context.Context, *emptypb.Empty) (*FetchMilestoneCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMilestoneCount not implemented")
}
func (UnimplementedIrisServer) FetchLastNoAckMilestone(context.Context, *emptypb.Empty) (*FetchLastNoAckMilestoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchLastNoAckMilestone not implemented")
}
func (UnimplementedIrisServer) FetchNoAckMilestone(context.Context, *FetchMilestoneNoAckRequest) (*FetchMilestoneNoAckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchNoAckMilestone not implemented")
}
func (UnimplementedIrisServer) FetchMilestoneID(context.Context, *FetchMilestoneIDRequest) (*FetchMilestoneIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMilestoneID not implemented")
}
func (UnimplementedIrisServer) mustEmbedUnimplementedIrisServer() {}

// UnsafeIrisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IrisServer will
// result in compilation errors.
type UnsafeIrisServer interface {
	mustEmbedUnimplementedIrisServer()
}

func RegisterIrisServer(s grpc.ServiceRegistrar, srv IrisServer) {
	s.RegisterService(&Iris_ServiceDesc, srv)
}

func _Iris_Span_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisServer).Span(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iris.Iris/Span",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisServer).Span(ctx, req.(*SpanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Iris_StateSyncEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StateSyncEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IrisServer).StateSyncEvents(m, &irisStateSyncEventsServer{stream})
}

type Iris_StateSyncEventsServer interface {
	Send(*StateSyncEventsResponse) error
	grpc.ServerStream
}

type irisStateSyncEventsServer struct {
	grpc.ServerStream
}

func (x *irisStateSyncEventsServer) Send(m *StateSyncEventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Iris_FetchCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisServer).FetchCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iris.Iris/FetchCheckpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisServer).FetchCheckpoint(ctx, req.(*FetchCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Iris_FetchCheckpointCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisServer).FetchCheckpointCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iris.Iris/FetchCheckpointCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisServer).FetchCheckpointCount(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Iris_FetchMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisServer).FetchMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iris.Iris/FetchMilestone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisServer).FetchMilestone(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Iris_FetchMilestoneCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisServer).FetchMilestoneCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iris.Iris/FetchMilestoneCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisServer).FetchMilestoneCount(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Iris_FetchLastNoAckMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisServer).FetchLastNoAckMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iris.Iris/FetchLastNoAckMilestone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisServer).FetchLastNoAckMilestone(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Iris_FetchNoAckMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchMilestoneNoAckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisServer).FetchNoAckMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iris.Iris/FetchNoAckMilestone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisServer).FetchNoAckMilestone(ctx, req.(*FetchMilestoneNoAckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Iris_FetchMilestoneID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchMilestoneIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisServer).FetchMilestoneID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iris.Iris/FetchMilestoneID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisServer).FetchMilestoneID(ctx, req.(*FetchMilestoneIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Iris_ServiceDesc is the grpc.ServiceDesc for Iris service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Iris_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iris.Iris",
	HandlerType: (*IrisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Span",
			Handler:    _Iris_Span_Handler,
		},
		{
			MethodName: "FetchCheckpoint",
			Handler:    _Iris_FetchCheckpoint_Handler,
		},
		{
			MethodName: "FetchCheckpointCount",
			Handler:    _Iris_FetchCheckpointCount_Handler,
		},
		{
			MethodName: "FetchMilestone",
			Handler:    _Iris_FetchMilestone_Handler,
		},
		{
			MethodName: "FetchMilestoneCount",
			Handler:    _Iris_FetchMilestoneCount_Handler,
		},
		{
			MethodName: "FetchLastNoAckMilestone",
			Handler:    _Iris_FetchLastNoAckMilestone_Handler,
		},
		{
			MethodName: "FetchNoAckMilestone",
			Handler:    _Iris_FetchNoAckMilestone_Handler,
		},
		{
			MethodName: "FetchMilestoneID",
			Handler:    _Iris_FetchMilestoneID_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StateSyncEvents",
			Handler:       _Iris_StateSyncEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "iris/iris.proto",
}
